= Debezium on OpenShift
:experimental: true
:product-name:
:version: 1.2.0

This cheat sheet covers how to deploy/create/update a Debezium Connector on OpenShift.

== What’s Debezium ?

Debezium is an open source distributed platform for change data capture. Start it up, point it at your databases, and your apps can start responding to all of the inserts, updates, and deletes that other apps commit to your databases. 
Debezium is durable and fast, so your apps can respond quickly and never miss an event, even when things go wrong.

== Deployments

Debezium is built on top of Apache Kafka on OpenShift (Strimzi), which is proven, scalable, and handles very large volumes of data very quickly:

<1> Creating a container image from the Kafka Connect base image using `Docker`:

[source, bash-shell, subs=attributes+]
----
export IMG_NAME="debezium-connect"
export DEBEZIUM_VERSION=1.2.0.Final

mkdir -p plugins && cd plugins && \
for PLUGIN in {mongodb,mysql,postgres}; do \
    curl https://repo1.maven.org/maven2/io/debezium/debezium-connector-$PLUGIN/$DEBEZIUM_VERSION/debezium-connector-$PLUGIN-$DEBEZIUM_VERSION-plugin.tar.gz | tar xz; \
done
cd ..
cat <<EOF > Dockerfile
FROM registry.redhat.io/amq7/amq-streams-kafka-24-rhel7:1.4.0
USER root:root
COPY ./plugins/ /opt/kafka/plugins/
USER 1001
EOF

oc new-build --binary --name=debezium-connect -l app=debezium-connect
oc patch bc/debezium-connect -p '{"spec":{"strategy":{"dockerStrategy":{"dockerfilePath":"Dockerfile"}}}}'
oc set build-secret --pull bc/debezium-connect registry-redhat-io
oc start-build debezium-connect --from-dir=. --follow

oc create -f - <<EOF
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: my-connect-cluster
  #annotations:
    #strimzi.io/use-connector-resources: "true"
spec:
  replicas: 1
  version: 2.4.0
  image: "image-registry.openshift-image-registry.svc:5000/strimzi/debezium-connect"
  bootstrapServers: my-cluster-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: my-cluster-cluster-ca-cert
        certificate: ca.crt
EOF
----

<2> Creating a container image using OpenShift builds and `Source-to-Image` (S2I):

[source, bash-shell, subs=attributes+]
----
export DEBEZIUM_VERSION=1.2.0.Final
mkdir -p plugins && cd plugins && \
for PLUGIN in {mongodb,mysql,postgres}; do \
    curl https://repo1.maven.org/maven2/io/debezium/debezium-connector-$PLUGIN/$DEBEZIUM_VERSION/debezium-connector-$PLUGIN-$DEBEZIUM_VERSION-plugin.tar.gz | tar xz; \
done && \
oc start-build my-connect-cluster-connect --from-dir=. --follow && \
cd .. && rm -rf plugins
----

TIP: You can generate the project in https://code.quarkus.io/ and selecting `kubernetes`, `kubernetes-client`, `health` and `kubernetes-config` extensions.

== Commands

Quarkus integrates with Fabric8 Kubernetes Client to access Kubernetes Server API.


`quarkus.kubernetes-client.trust-certs`::
Trust self-signed certificates, defaults to `false`.

== Logs

Change the log level to trace of `io.debezium` as follows:
[source, bash-shell, subs=attributes+]
----
oc exec -it my-connect-cluster-connect-2-xxxxx -- curl -s -X PUT -H "Content-Type:application/json"  http://localhost:8083/admin/loggers/io.debezium -d '{"level": "TRACE"}'
----

Revert the log level back to `INFO` as follows:
[source, bash-shell, subs=attributes+]
----
oc exec -it my-connect-cluster-connect-2-xxxxx -- curl -s -X PUT -H "Content-Type:application/json"  http://localhost:8083/admin/loggers/io.debezium -d '{"level": "INFO"}'
----
