= Debezium on OpenShift
:experimental: true
:product-name:
:version: 1.2.0

This cheat sheet covers how to deploy/create/update a Debezium Connector on OpenShift.

== What’s Debezium ?

Debezium is an open source distributed platform for change data capture. Start it up, point it at your databases, and your apps can start responding to all of the inserts, updates, and deletes that other apps commit to your databases. 
Debezium is durable and fast, so your apps can respond quickly and never miss an event, even when things go wrong.

== Deployments

Debezium is built on top of Apache Kafka on OpenShift (Strimzi), which is proven, scalable, and handles very large volumes of data very quickly:

1. Creating a container image from the Kafka Connect base image using `Docker`:

[source, bash-shell, subs=attributes+]
----
export IMG_NAME="debezium-connect"
export DEBEZIUM_VERSION=1.1.2.Final

mkdir -p plugins && cd plugins && \
for PLUGIN in {mongodb,mysql,postgres}; do \
    curl https://repo1.maven.org/maven2/io/debezium/debezium-connector-$PLUGIN/$DEBEZIUM_VERSION/debezium-connector-$PLUGIN-$DEBEZIUM_VERSION-plugin.tar.gz | tar xz; \
done
cd ..
cat <<EOF > Dockerfile
FROM registry.redhat.io/amq7/amq-streams-kafka-24-rhel7:1.4.0
USER root:root
COPY ./plugins/ /opt/kafka/plugins/
USER 1001
EOF

oc new-build --binary --name=debezium-connect -l app=debezium-connect
oc patch bc/debezium-connect -p '{"spec":{"strategy":{"dockerStrategy":{"dockerfilePath":"Dockerfile"}}}}'
oc set build-secret --pull bc/debezium-connect registry-redhat-io
oc start-build debezium-connect --from-dir=. --follow

oc create -f - <<EOF
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: my-connect-cluster
  #annotations:
    #strimzi.io/use-connector-resources: "true"
spec:
  replicas: 1
  version: 2.4.0
  image: "image-registry.openshift-image-registry.svc:5000/strimzi/debezium-connect"
  bootstrapServers: my-cluster-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: my-cluster-cluster-ca-cert
        certificate: ca.crt
EOF
----


2. Creating a container image using OpenShift builds and `Source-to-Image` (S2I):

[source, bash-shell, subs=attributes+]
----
export DEBEZIUM_VERSION=1.2.0.Final
mkdir -p plugins && cd plugins && \
for PLUGIN in {mongodb,mysql,postgres}; do \
    curl https://repo1.maven.org/maven2/io/debezium/debezium-connector-$PLUGIN/$DEBEZIUM_VERSION/debezium-connector-$PLUGIN-$DEBEZIUM_VERSION-plugin.tar.gz | tar xz; \
done && \
oc start-build my-connect-cluster-connect --from-dir=. --follow && \
cd .. && rm -rf plugins
----

TIP: You can generate the project in https://code.quarkus.io/ and selecting `kubernetes`, `kubernetes-client`, `health` and `kubernetes-config` extensions.

== Kubernetes

Quarkus use the `Dekorate` project to generate Kubernetes resources.

Running `./mvnw package` the Kubernetes resources are created at `target/kubernetes/` directory.

== Health Checks

The generated Kubernetes resources are integrated with MicroProfile Health spec, registering liveness/readiness probes based on the health checks defined using the spec.

If the extension is present, a default liveness/readiness probes are registered at `/health/live` and `/health/ready` endpoints.

You can implement a custom liveness/readiness probes:

[source, java]
----
import io.smallrye.health.HealthStatus;

@ApplicationScoped
public class DatabaseHealthCheck {

    @Liveness
    HealthCheck isAlive() {
      return HealthStatus.up("successful-live");
    }

    @Readiness
    HealthCheck isReady() {
      return HealthStatus.state("successful-read", this::isServiceReady)
    }

    private boolean isServiceReady() {
        return true;
    }
}
----

Quarkus comes with three health check implementations for checking the service status.

SocketHealthCheck:: It checks if the host is reachable using a socket.
UrlHealthCheck:: It checks if the host is reachable using a HTTP URL connection.
InetAddressHealthCheck:: It checks if host is reachable using `InetAddress.isReachable` method.

[source, java]
----
@Readiness
HealthCheck isGoogleReady() {
     return new UrlHealthCheck("https://www.google.com").name("Google-Check");
}
----

The following Quarkus extensions `agroal` (datasource), `kafka`, `mongoDB`, `neo4j`, `artemis`, `kafka-streams` and `vault` provide readiness health checks by default.

They can be enabled/disabled by setting `quarkus.<component>.health.enabled` to `true`/`false`.

[source, properties]
----
quarkus.kafka-streams.health.enabled=true
quarkus.mongodb.health.enabled=false
----

== Kubernetes Configuration

Kubernetes Config extension uses Kubernetes API Server to get `config-map`s and inject their key/value using MicroProfile Config spec.

You need to enable the extension and set name of the `config-map`s that contains the properties to inject: 

[source, properties]
----
quarkus.kubernetes-config.enabled=true
quarkus.kubernetes-config.config-maps=cmap1,cmap2
----

To inject `cmap1` and `cmap2` values, you need to set the key name in the `@ConfigProperty` annotation:

[source, java]
----
@ConfigProperty(name = "some.prop1")
String someProp1;

@ConfigProperty(name = "some.prop2")
String someProp2;
----

If the config key is a Quarkus configuration file, `application.properties` or `application.yaml`, the content of these files is parsed and each key/value of the configuration file can be injected as well.

List of Kubernetes Config parameters.

`quarkus.kubernetes-config.enabled`::
The application will attempt to look up the configuration from the API server, defaults to `false`.

`quarkus.kubernetes-config.fail-on-missing-config`::
The application will not start if any of the configured config sources cannot be located, defaults to `true`.

`quarkus.kubernetes-config.config-maps`::
ConfigMaps to look for in the namespace that the Kubernetes Client has been configured for. Supports CSV format.

== Kubernetes Client

Quarkus integrates with Fabric8 Kubernetes Client to access Kubernetes Server API.

[source, java]
----
@Inject
KubernetesClient client;

ServiceList myServices = client.services().list();

Service myservice = client.services()
        .inNamespace("default")
        .withName("myservice")
        .get();
----

Kubernetes Client can be configured programmatically:

[source, java]
----
@Dependent
public class KubernetesClientProducer {

    @Produces
    public KubernetesClient kubernetesClient() {
        Config config = new ConfigBuilder()
            .withMasterUrl("https://mymaster.com")
            .build();
        return new DefaultKubernetesClient(config);
    }
}
----

Or also in `application.properties`.

By default, Kubernetes Client reads connection properties from the `~/.kube/config` folder but you can set them too by using some of the `kubernetes-client` properties:

`quarkus.kubernetes-client.trust-certs`::
Trust self-signed certificates, defaults to `false`.

`quarkus.kubernetes-client.master-url`::
URL of Kubernetes API server.

`quarkus.kubernetes-client.namespace`::
Default namespace.

`quarkus.kubernetes-client.ca-cert-file`::
CA certificate data.

`quarkus.kubernetes-client.client-cert-file`::
Client certificate file.

`quarkus.kubernetes-client.client-cert-data`::
Client certificate data.

`quarkus.kubernetes-client.client-key-data`::
Client key data.

`quarkus.kubernetes-client.client-key-algorithm`::
Client key algorithm.

`quarkus.kubernetes-client.username`::
Username.

`quarkus.kubernetes-client.password`::
Password.
