= Debezium on OpenShift
:experimental: false
:product-name: Debezium
:version: 1.2.0

This cheat sheet covers how to deploy/create/run/update a Debezium Connector on OpenShift.

== What’s Debezium ?

Debezium is an open source distributed platform for change data capture. Start it up, point it at your databases, and your apps can start responding to all of the inserts, updates, and deletes that other apps commit to your databases. 
Debezium is durable and fast, so your apps can respond quickly and never miss an event, even when things go wrong.

== Deployments

Debezium is built on top of Apache Kafka on `Kubernetes` and `OpenShift` with the https://strimzi.io[Strimzi] project. `Strimzi` provides a set of operators and container images for running Kafka on Kubernetes and OpenShift. 

Extend Kafka Connect with Debezium Binaries: 

<1> `Docker`:

[source, bash,indent=0]
----
export IMG_NAME="debezium-connect"
export DEBEZIUM_VERSION=1.2.0.Final

mkdir -p plugins && cd plugins && \
for PLUGIN in {mongodb,mysql,postgres}; do \
    curl https://repo1.maven.org/maven2/io/debezium/debezium-connector-$PLUGIN/$DEBEZIUM_VERSION/debezium-connector-$PLUGIN-$DEBEZIUM_VERSION-plugin.tar.gz | tar xz; \
done
cd ..
cat <<EOF > Dockerfile
FROM registry.redhat.io/amq7/amq-streams-kafka-24-rhel7:1.4.0
USER root:root
COPY ./plugins/ /opt/kafka/plugins/
USER 1001
EOF

oc new-build --binary --name=$IMG_NAME -l app=$IMG_NAME
oc patch bc/$IMG_NAME -p '{"spec":{"strategy":{"dockerStrategy":{"dockerfilePath":"Dockerfile"}}}}'
oc start-build $IMG_NAME --from-dir=. --follow

oc create -f - <<EOF
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: $IMG_NAME
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  replicas: 1
  version: 2.4.0
  image: "image-registry.openshift-image-registry.svc:5000/strimzi/$IMG_NAME"
  bootstrapServers: my-cluster-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: my-cluster-cluster-ca-cert
        certificate: ca.crt
EOF
----

<2> `Source-to-Image` (S2I):

[source, bash,indent=0]
----
export DEBEZIUM_VERSION=1.2.0.Final
mkdir -p plugins && cd plugins && \
for PLUGIN in {mongodb,mysql,postgres}; do \
    curl https://repo1.maven.org/maven2/io/debezium/debezium-connector-$PLUGIN/$DEBEZIUM_VERSION/debezium-connector-$PLUGIN-$DEBEZIUM_VERSION-plugin.tar.gz | tar xz; \
done && \
oc start-build my-connect-cluster-connect --from-dir=. --follow && \
cd .. && rm -rf plugins
----

TIP: You can generate the project in https://code.quarkus.io/ and selecting `kubernetes`, `kubernetes-client`, `health` and `kubernetes-config` extensions.

== Commands

Quarkus integrates with Fabric8 Kubernetes Client to access Kubernetes Server API.

[source, bash,indent=0]
----
export DEBEZIUM_SVC=my-connect-cluster-connect-connect-api
export CONNECTOR=inventory-connector-mysql
----

=== Create Debezium Connector

[source, bash,indent=0]
----
oc exec -i my-cluster-kafka-0 -- curl -X POST \
    -H "Accept:application/json" \
    -H "Content-Type:application/json" \
    http://$DEBEZIUM_SVC:8083/connectors -d @- <<'EOF'
{
    "name": "$CONNECTOR",
    "config": {
        "connector.class": "io.debezium.connector.mysql.MySqlConnector",
        "tasks.max": "1",
        "database.hostname": "mysql",
        "database.port": "3306",
        "database.user": "debezium",
        "database.password": "dbz",
        "database.server.id": "184054",
        "database.server.name": "dbserver",
        "database.whitelist": "inventory",
        "database.history.kafka.bootstrap.servers": "my-cluster-kafka-bootstrap:9092",
        "database.history.kafka.topic": "schema-changes.inventory"
    }
}
EOF
----

=== Get Connector Details

[source, bash,indent=0]
----
oc exec -i my-cluster-kafka-0 -- curl -X GET \
    -H "Accept:application/json" \
    -H "Content-Type:application/json" \
    http://debezium-marketing-connector-connect-api:8083/connectors
----

=== Update Connector

[source, bash,indent=0]
----
oc exec -i my-cluster-kafka-0 -- curl -i -X PUT -H "Accept:application/json" -H "Content-Type:application/json" http://$DEBEZIUM_SVC:8083/connectors/$CONNECTOR/config/ -d @- <<'EOF'
{
        "connector.class": "io.debezium.connector.mysql.MySqlConnector",
        "tasks.max": "1",
        "database.hostname": "mysql",
        "database.port": "3306",
        "database.user": "debezium",
        "database.password": "dbz",
        "database.server.id": "184054",
        "database.server.name": "dbserver",
        "database.whitelist": "inventory",
        "database.history.kafka.bootstrap.servers": "my-cluster-kafka-bootstrap:9092",
        "database.history.kafka.topic": "schema-changes.inventory",
        "transforms": "unwrap, order_date",
        "transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState",
        "transforms.unwrap.drop.tombstones": "false",
        "transforms.unwrap.operation.header": "true",
        "transforms.order_date.type": "org.apache.kafka.connect.transforms.TimestampConverter$Value",
        "transforms.order_date.target.type": "string",
        "transforms.order_date.field": "order_date",
        "transforms.order_date.format": "yyyy/MM/dd",
        "key.converter": "org.apache.kafka.connect.json.JsonConverter",
        "key.converter.schemas.enable": "false",
        "value.converter": "org.apache.kafka.connect.json.JsonConverter",
        "value.converter.schemas.enable": "false",
        "time.precision.mode": "connect",
        "include.schema.changes": "false"
    }
}
EOF
----

=== Delete Connector

[source, bash,indent=0]
----
oc exec -i my-cluster-kafka-0 -- curl -X DELETE \
    -H "Accept:application/json" \
    -H "Content-Type:application/json" \
    http://debezium-marketing-connector-connect-api:8083/connectors/inventory-connector
----

=== Get Connectors

[source, bash,indent=0]
----
oc exec -i my-cluster-kafka-0 -- curl -X GET \
    -H "Accept:application/json" \
    -H "Content-Type:application/json" \
    http://debezium-marketing-connector-connect-api:8083/connectors
----

=== Check connector status

[source, bash,indent=0]
----
oc exec -i my-cluster-kafka-0 -- curl -X GET \
    -H "Accept:application/json" \
    -H "Content-Type:application/json" \
    http://debezium-marketing-connector-connect-api:8083/connectors/inventory-connector/status
----

=== check the available connector plugins:

[source, bash,indent=0]
----
oc exec -i my-cluster-kafka-0 -- curl -X GET \
    -H "Accept:application/json" \
    -H "Content-Type:application/json" \
    http://debezium-marketing-connector-connect-api:8083/connector-plugins
----

== Logs

Change the log level to trace of `io.debezium` as follows:
[source, bash,indent=0]
----
oc exec -it my-connect-cluster-connect-2-xxxxx -- curl -s -X PUT -H "Content-Type:application/json"  http://localhost:8083/admin/loggers/io.debezium -d '{"level": "TRACE"}'
----

Revert the log level back to `INFO` as follows:
[source, bash,indent=0]
----
oc exec -it my-connect-cluster-connect-2-xxxxx -- curl -s -X PUT -H "Content-Type:application/json"  http://localhost:8083/admin/loggers/io.debezium -d '{"level": "INFO"}'
----
