= Red Hat Enterprise Linux 8 Beta
:product-name: RHEL

We are delighted to introduce you to Red Hat Enterprise Linux 8 Beta. If you’re familiar with previous versions of Red Hat Enterprise Linux, you’ll find RHEL 8 Beta
more intuitive to pick up and use. However, there are a few new features and changes that you’ll want to be aware of, so we hope this cheat sheet will help you
quickly explore and begin your RHEL 8 Beta application development.

== Simplified software packaging and installation

Installing and using RHEL 8 Beta is much easier than previous releases.
Previously, there were server, workstation, and desktop variants, but RHEL 8 Beta has only one distribution (ISO file) for each architecture.
The RHEL 8 Beta has also been simplified with fewer repos - they are:

- `BaseOS Beta` - primarily core operating system packages with support for the lifetime of the OS
- `AppStream Beta` - user-space applications and components, including numerous Application Streams that will be updated on a more frequent cadence
- `Linux Builder Beta` - a collection of unsupported developer tools
- `Supplementary` - 3rd party support only

Compilers, runtimes, web/database servers, and development tools will generally be delivered as Application Streams from the AppStream repo.
See below for more info.

== Basic Red Hat Enterprise Linux commands

The most basic tasks that you might need after the operating system has been installed include:

`yum search string`:: search for packages matching a specific string

`yum install package_name`:: install a package

`yum update package_name`:: update a package

`yum remove package_name`:: uninstall a package and any packages that depend on it

`yum list all`:: list information on all installed and available packages

`yum list installed`:: list all installed packages

== Working with containers

To enable container management without the need for daemons, Red Hat has <<introduced, introduced>> a set of tools for your Linux container application development:

- Buildah allows you to build a container without any daemon or docker.

- Podman allows you to manage containers without the daemon dependency it’s also docker cli compatible.

You can obtain a number of RHEL 8 Beta container images from the Red Hat container <<catalog, catalog>>.

`subscription-manager repos --list`:: list all available repositories

`yum repolist`:: list all currently enabled repositories

`subscription-manager repos --enable repository`:: enable a repository

`subscription-manager repos —disable repository`:: disable a repository

== Working with containers

The most basic tasks that you might need after the operating system has been installed include:

`yum module list`:: list all modules

`yum module list installed`:: list installed modules

== Simplified software packaging and installation

Installing and using RHEL 8 Beta is much easier than previous releases.
Previously, there were server, workstation, and desktop variants, but RHEL 8 Beta has only one distribution (ISO file) for each architecture.
The RHEL 8 Beta has also been simplified with fewer repos - they are:

- `BaseOS Beta` - primarily core operating system packages with support for the lifetime of the OS
- `AppStream Beta` - user-space applications and components, including numerous Application Streams that will be updated on a more frequent cadence
- `Linux Builder Beta` - a collection of unsupported developer tools
- `Supplementary` - 3rd party support only

Compilers, runtimes, web/database servers, and development tools will generally be delivered as Application Streams from the AppStream repo.
See below for more info.

== Basic Red Hat Enterprise Linux commands

The most basic tasks that you might need after the operating system has been installed include:

`yum search string`:: search for packages matching a specific string

`yum install package_name`:: install a package

`yum update package_name`:: update a package

`yum remove package_name`:: uninstall a package and any packages that depend on it

`yum list all`:: list information on all installed and available packages

`yum list installed`:: list all installed packages

== Workng with containers

To enable container management without the need for daemons, Red Hat has <<introduced, introduced>> a set of tools for your Linux container application development:

- Buildah allows you to build a container without any daemon or docker.

- Podman allows you to manage containers without the daemon dependency it’s also docker cli compatible.

You can obtain a number of RHEL 8 Beta container images from the Red Hat container <<catalog, catalog>>.

`subscription-manager repos --list`:: list all available repositories

`yum repolist`:: list all currently enabled repositories

`subscription-manager repos --enable repository`:: enable a repository

`subscription-manager repos —disable repository`:: disable a repository

== Working with containers

The most basic tasks that you might need after the operating system has been installed include:

`yum module list`:: list all modules

`yum module list installed`:: list installed modules
