= RHEL 8 Cheat Sheet
:experimental: true
:product-name:
:version: 1.0.0

Version 8 of Red Hat Enterprise Linux (RHEL) provides an upgraded package manager that replaces the classic `yum` application. This new package manager is named `dnf`, which is an abbreviation for _Dandified yum_.

RHEL 8 also ships with two related useful features:

Subscription Manager::
This keeps track of the various remote repositories that host application packages. The Subscription Manager does the work of binding to a repository, so developers don't have to write code to do the binding.

Application Streams::
This provides the ability to run multiple versions of a given program or module on a local machine, allowing a developer to switch between different versions on demand. The developer doesn't have to manage the details of upgrading or downgrading an application or module. For example, a developer can install Node.js version 10 and then later upgrade to Node.js version 16, leaving both versions available in different streams. The developer can run version 10 of Node.js to meet a special need for an old application, and quickly switch to version 16 when that version is needed.

This cheat sheet covers the basic `dnf` commands along with an introduction to Subscription Manager and application streams. In addition, the commands for installing many popular modules, applications, and programming languages are shown at the end of the cheat sheet.

== Basic dnf commands

The following sections show `dnf` command that can be used to search for modules, learn the details about a module, and install a module.

=== dnf search

----
dnf [options] search <search_string>
----

Searches for packages whose names or summaries contain `<search_string>`.

*Example:*

The following command uses `dnf search` to search for packages according to the search string criteria `perl-MAIL`:

----
$ sudo dnf search perl-MAIL
Updating Subscription Management repositories.
Last metadata expiration check: 3:35:27 ago on Wed 02 Feb 2022 05:08:48 AM PST.
========================== Name Matched: perl-MAIL ==============================
perl-Mail-Box.noarch : Manage a mailbox, a folder with messages
perl-Mail-DKIM.noarch : Sign and verify Internet mail with DKIM/DomainKey signatures
perl-Mail-IMAPClient.noarch : An IMAP Client API
perl-Mail-Message.noarch : MIME message handling
perl-Mail-RFC822-Address.noarch : Perl extension for validating email addresses according to RFC822
perl-Mail-SPF.noarch : Object-oriented implementation of Sender Policy Framework
perl-Mail-SPF_XS.x86_64 : An XS implementation of Mail::SPF
perl-Mail-Sender.noarch : Module for sending mails with attachments through an SMTP server
perl-Mail-Sendmail.noarch : Simple platform independent mailer for Perl
perl-Mail-Transport.noarch : Email message exchange
perl-MailTools.noarch : Various ancient mail-related perl modules
----

=== dnf info

----
dnf info <module_name>
----

Displays details about the named module.

*Example:*

The following command uses `dnf info` to display the details about the `dotnet`  module:

----
$ dnf info dotnet
Not root, Subscription Management repositories not updated
Last metadata expiration check: 0:41:52 ago on Tue 01 Feb 2022 09:19:22 AM PST.
Installed Packages
Name         : dotnet
Version      : 6.0.101
Release      : 2.el8_5
Architecture : x86_64
Size         : 0.0
Source       : dotnet6.0-6.0.101-2.el8_5.src.rpm
Repository   : @System
From repo    : rhel-8-for-x86_64-appstream-rpms
Summary      : .NET CLI tools and runtime
URL          : https://github.com/dotnet/
License      : MIT and ASL 2.0 and BSD and LGPLv2+ and CC-BY and CC0 and MS-PL and EPL-1.0 and GPL+ and GPLv2 and ISC and OFL and zlib
Description  : .NET is a fast, lightweight and modular platform for creating
             : cross platform applications that work on Linux, macOS and Windows.
             :
             : It particularly focuses on creating console applications, web
             : applications and micro-services.
             :
             : .NET contains a runtime conforming to .NET Standards a set of
             : framework libraries, an SDK containing compilers and a 'dotnet'
             : application to drive everything.
----

=== dnf install

----
dnf install [options] <module_name>
----

Installs a module on the local machine.

*Example:*

The following command installs the `perl` programming language on the local computer. The command uses the `-y` option to suppress the prompt that asks the user for permission to proceed:

----
sudo dnf install -y perl
----

The command produces too much screen output to show here.

=== dnf update

----
dnf update [options] <module_name>
----

Updates a module on the local machine.

*Example:*

The following command updates the `perl` programming language on the local computer. The command uses the `-y` option to suppress the prompt asking the user for permission to proceed:

----
$ sudo dnf update -y perl
Updating Subscription Management repositories.
Last metadata expiration check: 2:58:35 ago on Thu 27 Jan 2022 08:48:07 AM PST.
Dependencies resolved.
Nothing to do.
Complete!
----

=== dnf remove

----
dnf remove [options] <module_name>
----

Removes a module from the local machine.

*Example:*

The following command removes the `podman` application from the local computer. The command uses the `-y` option to allow installation to proceed without user confirmation:

----
$ sudo dnf remove  -y podman
Updating Subscription Management repositories.
Dependencies resolved.
===================================================================================================================================
 Package                      Architecture   Version                                    Repository                           Size
===================================================================================================================================
Removing:
 podman                        x86_64        1:3.4.2-9.module+el8.5.0+13852+150547f7     @rhel-8-for-x86_64-appstream-rpms   48 M
Removing dependent packages:
 cockpit-podman                noarch        33-1.module+el8.5.0+12582+56d94c81          @AppStream                          438 k
Removing unused dependencies:
 conmon                        x86_64        2:2.0.29-1.module+el8.5.0+12582+56d94c81    @AppStream                          164 k
 podman-catatonit              x86_64        1:3.4.2-9.module+el8.5.0+13852+150547f7     @rhel-8-for-x86_64-appstream-rpms   764 k

Transaction Summary
===================================================================================================================================
Remove  4 Packages

Freed space: 50 M
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                        1/1
  Running scriptlet: cockpit-podman-33-1.module+el8.5.0+12582+56d94c81.noarch               1/1
  Erasing          : cockpit-podman-33-1.module+el8.5.0+12582+56d94c81.noarch               1/4
  Erasing          : podman-1:3.4.2-9.module+el8.5.0+13852+150547f7.x86_64                  2/4
  Running scriptlet: podman-1:3.4.2-9.module+el8.5.0+13852+150547f7.x86_64                  2/4
  Erasing          : podman-catatonit-1:3.4.2-9.module+el8.5.0+13852+150547f7.x86_64        3/4
  Erasing          : conmon-2:2.0.29-1.module+el8.5.0+12582+56d94c81.x86_64                 4/4
  Running scriptlet: conmon-2:2.0.29-1.module+el8.5.0+12582+56d94c81.x86_64                 4/4
  Verifying        : cockpit-podman-33-1.module+el8.5.0+12582+56d94c81.noarch               1/4
  Verifying        : conmon-2:2.0.29-1.module+el8.5.0+12582+56d94c81.x86_64                 2/4
  Verifying        : podman-1:3.4.2-9.module+el8.5.0+13852+150547f7.x86_64                  3/4
  Verifying        : podman-catatonit-1:3.4.2-9.module+el8.5.0+13852+150547f7.x86_64        4/4
Installed products updated.

Removed:
  cockpit-podman-33-1.module+el8.5.0+12582+56d94c81.noarch conmon-2:2.0.29-1.module+el8.5.0+12582+56d94c81.x86_64
  podman-1:3.4.2-9.module+el8.5.0+13852+150547f7.x86_64  podman-catatonit-1:3.4.2-9.module+el8.5.0+13852+150547f7.x86_64

Complete!
----

=== dnf history

----
dnf [options] history <subcommand> <subcommand> ....
----

Shows or changes the actions taken by previous `dnf` commands executed on a system.

*Examples:*

The following command uses `dnf history` to report the most recent actions taken by the developer through `dnf`:

----
$ sudo dnf history
Updating Subscription Management repositories.
ID     | Command line                        | Date and time    | Action(s)      | Altered
-----------------------------------------------------------------------------------------
    14 | install dotnet                      | 2022-02-01 09:54 | Install        |   12
    13 | remove ant                          | 2022-02-01 09:37 | Removed        |    6
    12 | install ant                         | 2022-02-01 09:36 | Install        |    6
    11 | module install scala:2.10           | 2022-02-01 09:24 | Install        |   11
    10 | remove -y perl                      | 2022-01-27 11:47 | Removed        |  113
     9 | install perl                        | 2022-01-27 11:42 | Install        |  113
     8 | history undo last                   | 2022-01-26 09:23 | Removed        |   12
     7 | install dotnet                      | 2022-01-26 08:34 | Install        |   12
     6 | install ufw                         | 2022-01-24 09:15 | Install        |    1
     5 | install https://dl.fedoraproj...    | 2022-01-24 09:15 | Install        |    1
     4 | install traceroute                  | 2022-01-20 11:51 | Install        |    1
     3 | install iotop                       | 2022-01-19 09:57 | Install        |    1
     2 | -y install httpd mariadb-server     | 2022-01-14 10:04 | Install        |   19
     1 |
----

The following command uses `sudo dnf history undo last` to undo the most recent action, which in this case is the installation of the `dotnet` module. The example shows a portion of the screen output:

----
$ sudo dnf history undo last
Updating Subscription Management repositories.
Last metadata expiration check: 3:47:28 ago on Wed 02 Feb 2022 05:08:48 AM PST.
Dependencies resolved.
===========================================================================================================================
 Package                            Architecture       Version             Repository                          Size
===========================================================================================================================
Removing:
 dotnet                              x86_64        6.0.101-2.el8_5     @rhel-8-for-x86_64-appstream-rpms   0
Removing dependent packages:
 aspnetcore-runtime-6.0              x86_64        6.0.1-2.el8_5           @rhel-8-for-x86_64-appstream-rpms   21 M
 aspnetcore-targeting-pack-6.0       x86_64        6.0.1-2.el8_5           @rhel-8-for-x86_64-appstream-rpms   13 M
 dotnet-apphost-pack-6.0             x86_64        6.0.1-2.el8_5           @rhel-8-for-x86_64-appstream-rpms   11 M
 dotnet-host                         x86_64        6.0.1-2.el8_5           @rhel-8-for-x86_64-appstream-rpms   200 k
 dotnet-hostfxr-6.0                  x86_64        6.0.1-2.el8_5           @rhel-8-for-x86_64-appstream-rpms   345 k
 dotnet-runtime-6.0                  x86_64        6.0.1-2.el8_5           @rhel-8-for-x86_64-appstream-rpms   65 M
 dotnet-sdk-6.0                      x86_64        6.0.101-2.el8_5         @rhel-8-for-x86_64-appstream-rpms   268 M
 dotnet-targeting-pack-6.0           x86_64        6.0.1-2.el8_5           @rhel-8-for-x86_64-appstream-rpms   26 M
 dotnet-templates-6.0                x86_64        6.0.101-2.el8_5         @rhel-8-for-x86_64-appstream-rpms   6.2 M
 lttng-ust                           x86_64        2.8.1-11.el8            @rhel-8-for-x86_64-appstream-rpms   1.1 M
 netstandard-targeting-pack-2.1      x86_64        6.0.101-2.el8_5         @rhel-8-for-x86_64-appstream-rpms   18 M

Transaction Summary
===========================================================================================================================

Freed space: 430 M
Is this ok [y/N]:
.
.
.
----

=== dnf list

----
dnf list <subcommand> [options]
----

Lists modules on the system.

*Examples:*

The following command uses the `installed` subcommand to list installed modules. The result is piped to the `more` command, which shows the first 15 lines of output using the `-15` option:

----
$ sudo dnf list installed | more -15
Updating Subscription Management repositories.
Installed Packages
GConf2.x86_64                                      3.2.6-22.el8                                   @AppStream
ModemManager.x86_64                                1.10.8-4.el8                                   @anaconda
ModemManager-glib.x86_64                           1.10.8-4.el8                                   @anaconda
NetworkManager.x86_64                              1:1.32.10-4.el8                                @anaconda
NetworkManager-adsl.x86_64                         1:1.32.10-4.el8                                @anaconda
NetworkManager-bluetooth.x86_64                    1:1.32.10-4.el8                                @anaconda
NetworkManager-config-server.noarch                1:1.32.10-4.el8                                @anaconda
NetworkManager-libnm.x86_64                        1:1.32.10-4.el8                                @anaconda
NetworkManager-team.x86_64                         1:1.32.10-4.el8                                @anaconda
NetworkManager-tui.x86_64                          1:1.32.10-4.el8                                @anaconda
NetworkManager-wifi.x86_64                         1:1.32.10-4.el8                                @anaconda
NetworkManager-wwan.x86_64                         1:1.32.10-4.el8                                @anaconda
PackageKit.x86_64                                  1.1.12-6.el8                                   @AppStream
--More--
----

The following command uses the `all` subcommand to show all modules. The result is piped to the `more` command, which uses the `-15` option to show the first 15 lines of output:

----
$ sudo dnf list all | more -15
Updating Subscription Management repositories.
Last metadata expiration check: 4:00:42 ago on Wed 02 Feb 2022 05:08:48 AM PST.
Installed Packages
GConf2.x86_64                                3.2.6-22.el8                            @AppStream
ModemManager.x86_64                          1.10.8-4.el8                            @anaconda
ModemManager-glib.x86_64                     1.10.8-4.el8                            @anaconda
NetworkManager.x86_64                        1:1.32.10-4.el8                         @anaconda
NetworkManager-adsl.x86_64                   1:1.32.10-4.el8                         @anaconda
NetworkManager-bluetooth.x86_64              1:1.32.10-4.el8                         @anaconda
NetworkManager-config-server.noarch          1:1.32.10-4.el8                         @anaconda
NetworkManager-libnm.x86_64                  1:1.32.10-4.el8                         @anaconda
NetworkManager-team.x86_64                   1:1.32.10-4.el8                         @anaconda
NetworkManager-tui.x86_64                    1:1.32.10-4.el8                         @anaconda
NetworkManager-wifi.x86_64                   1:1.32.10-4.el8                         @anaconda
NetworkManager-wwan.x86_64                   1:1.32.10-4.el8                         @anaconda
--More--
----

=== dnf repolist

----
dnf repolist
----

Lists the remote package repositories registered on the local machines. Must be entered as root (superuser).

*Example:*

The following command uses `dnf repolist` to list the remote package repositories registered on the local machines:

----
$ sudo dnf repolist
Updating Subscription Management repositories.
repo id                                         repo name
epel                                            Extra Packages for Enterprise Linux 8 - x86_64
epel-modular                                    Extra Packages for Enterprise Linux Modular 8 - x86_64
rhel-8-for-x86_64-appstream-rpms                Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)
rhel-8-for-x86_64-baseos-rpms                   Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)
----

== Working with Subscription Manager

The Subscription Manager is a client-side program that provides a command-line interface (CLI) to the RHEL Subscription Management service. The Subscription Manager coordinates access, monitoring, and getting information about RHEL applications and modules. The following sections describe the various commands available through the Subscription Manager command.

=== subscription-manager repos

Enables access to a remote package repository via the Subscription Manager.

*Examples:*

The following command uses the `repos` subcommand to list the various artifact repositories available via the Subscription Manager. The `repos` subcommand requires root access. The command prompts for the root password if it is not executed as root.

The following belows shows only a portion of the full output:

----
$ subscription-manager repos
You are attempting to run "subscription-manager" which requires administrative
privileges, but more information is needed in order to do so.
Authenticating as "root"
Password:
+----------------------------------------------------------+
    Available Repositories in /etc/yum.repos.d/redhat.repo
+----------------------------------------------------------+
Repo ID:   rhel-8-for-x86_64-sap-solutions-e4s-rpms
Repo Name: Red Hat Enterprise Linux 8 for x86_64 - SAP Solutions - Update Services for SAP Solutions (RPMs)
Repo URL:  https://cdn.redhat.com/content/e4s/rhel8/$releasever/x86_64/sap-solutions/os
Enabled:   0

Repo ID:   jpp-textonly-1-for-middleware-rpms
Repo Name: Red Hat JBoss Portal Text-Only Advisories
Repo URL:  https://cdn.redhat.com/content/dist/middleware/jpp/1.0/$basearch/os
Enabled:   0

Repo ID:   jb-datagrid-8.1-for-rhel-8-x86_64-source-rpms
Repo Name: Red Hat JBoss Data Grid 8.1 (RHEL 8) (Source RPMs)
Repo URL:  https://cdn.redhat.com/content/dist/layered/rhel8/x86_64/jdg/8.1/source/SRPMS
Enabled:   0

Repo ID:   jb-datagrid-8.1-for-rhel-8-x86_64-debug-rpms
Repo Name: Red Hat JBoss Data Grid 8.1 (RHEL 8) (Debug RPMs)
Repo URL:  https://cdn.redhat.com/content/dist/layered/rhel8/x86_64/jdg/8.1/debug
Enabled:   0
.
.
.
----

The following command enables access from the local computer to the repository `jb-datagrid-8.1-for-rhel-8-x86_64-source-rpms`:

----
$ subscription-manager repos --enable jb-datagrid-8.1-for-rhel-8-x86_64-source-rpms
You are attempting to run "subscription-manager" which requires administrative
privileges, but more information is needed in order to do so.
Authenticating as "root"
Password:
Repository 'jb-datagrid-8.1-for-rhel-8-x86_64-source-rpms' is enabled for this system.
----

The following command disables access from the local computer to the repository `jb-datagrid-8.1-for-rhel-8-x86_64-source-rpms`:

----
$ subscription-manager repos --disable jb-datagrid-8.1-for-rhel-8-x86_64-source-rpms
You are attempting to run "subscription-manager" which requires administrative
privileges, but more information is needed in order to do so.
Authenticating as "root"
Password:
Repository 'jb-datagrid-8.1-for-rhel-8-x86_64-source-rpms' is disabled for this system.
----

== Working with Application Streams

Red Hat Enterprise Linux 8 supports application streams. Application streaming is a type of on-demand software distribution allowing easy access to several versions of a particular application or module on a computer. Application streams allow the user to switch between versions of an application or module to meet the particular need at hand.

The base command for working with application streams is `dnf module`. Particular actions are executed using subcommands. The sections that follow show how to use the various subcommands associated with `dnf module`.

=== dnf module info

----
dnf module info [options] <module_name>:<version_number>
----

Displays the details about a module.

*Examples:*

The following command uses the `--profile` option to get a listing of all modules associated with the Redis database/message broker:

----
$ sudo dnf module info --profile redis
Updating Subscription Management repositories.
Last metadata expiration check: 4:22:55 ago on Tue 08 Feb 2022 05:00:14 AM PST.
Name   : redis:5:8000020190711140130:f8e95b4e:x86_64
common : redis

Name   : redis:5:8040020211011074037:522a0ee4:x86_64
common : redis

Name   : redis:5:820181217094919:9edba152:x86_64
common : redis

Name   : redis:6:8040020201124072123:9f9e2e7e:x86_64
common : redis

Name   : redis:6:8040020210512055424:522a0ee4:x86_64
common : redis

Name   : redis:6:8040020211011082941:522a0ee4:x86_64
common : redis
----

The following command uses `dnf module info` to get the details of the `Redis` module, version `redis:5:820181217094919:9edba152:x86_64`:

----
$ sudo dnf module info redis:5:820181217094919:9edba152:x86_64
Updating Subscription Management repositories.
Last metadata expiration check: 0:10:55 ago on Tue 08 Feb 2022 09:25:36 AM PST.
Name             : redis
Stream           : 5 [d][a]
Version          : 820181217094919
Context          : 9edba152
Architecture     : x86_64
Profiles         : common [d]
Default profiles : common
Repo             : rhel-8-for-x86_64-appstream-rpms
Summary          : Redis persistent key-value database
Description      : redis 5 module
Requires         : platform:[el8]
Artifacts        : redis-0:5.0.3-1.module+el8+2566+19ca22c8.x86_64
                 : redis-devel-0:5.0.3-1.module+el8+2566+19ca22c8.x86_64
                 : redis-doc-0:5.0.3-1.module+el8+2566+19ca22c8.noarch

Hint: [d]efault, [e]nabled, [x]disabled, [i]nstalled, [a]ctive
----

=== dnf module list

`dnf module [options] list <module_name>`

Reports the status of modules that are available from a remote Red Hat Enterprise Linux repository or downloaded to the local computer. The command is used with the following options to filter the list:

`--all`::
Lists all packages present on the system, in a repository, or both.

`--installed`::
Lists packages installed on the system..

`--available`::
Lists available packages..

`--obsoletes`::
Lists packages installed on the system that are deemed obsolete in any known repository..

Run the command as root to update the repository reference on the local machine.

*Example:*

The following command uses the `--installed` option to show the modules that are presently running on the local computer, and ensures they are up to date:

----
$ sudo dnf module list --installed
Updating Subscription Management repositories.
Last metadata expiration check: 1:46:30 ago on Wed 09 Feb 2022 08:06:21 AM PST.
Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)
Name         Stream      Profiles                                   Summary
nodejs       12 [e]      common [d] [i], development, minimal, s2i  Javascript runtime
redis        6 [e]       common [d] [i]                             Redis persistent key-value database

Hint: [d]efault, [e]nabled, [x]disabled, [i]nstalled

----

=== dnf module provides

----
dnf module provides <provide_spec>
----

Describes the repositories that provide a module according to the `<provide_spec>`. `<provide_spec>` can specify a module name, a module's filepath, or a particular version of a module.

*Example:*

The following command uses `dnf provides` to discover which repositories–local and remote–provide the `gzip` module:

----
$ sudo dnf provides /usr/bin/gzip
Updating Subscription Management repositories.
Last metadata expiration check: 3:20:01 ago on Wed 02 Feb 2022 05:08:48 AM PST.
gzip-1.9-4.el8.x86_64 : The GNU data compression program
Repo        : rhel-8-for-x86_64-baseos-rpms
Matched from:
Filename    : /usr/bin/gzip

gzip-1.9-9.el8.x86_64 : The GNU data compression program
Repo        : rhel-8-for-x86_64-baseos-rpms
Matched from:
Filename    : /usr/bin/gzip

gzip-1.9-12.el8.x86_64 : The GNU data compression program
Repo        : @System
Matched from:
Filename    : /usr/bin/gzip

gzip-1.9-12.el8.x86_64 : The GNU data compression program
Repo        : rhel-8-for-x86_64-baseos-rpms
Matched from:
Filename    : /usr/bin/gzip.
----

=== dnf module enable

----
dnf module [options] enable <module>:<stream>
----

Enables a particular stream of a module. Enabling a module provides system access to the repository packages in that module stream.

*Example:*

The following command enables stream 2.10 of the `scala` module:

----
$ sudo dnf module enable scala:2.10
Updating Subscription Management repositories.
Last metadata expiration check: 0:18:54 ago on Fri 28 Jan 2022 11:32:49 AM PST.
Dependencies resolved.
================================================================================================
 Package                                             Architecture  Version   Repository  Size
================================================================================================
Enabling module streams:
 scala                                                              2.10

Transaction Summary
================================================================================================

Is this ok [y/N]:
Complete!
----

=== dnf module remove

----
dnf module remove <module_name:stream>
----

Removes a module from the local computer.

*Example:*

The following command removes the `ant` module from the local computer:

----
$ sudo dnf module remove ant
Updating Subscription Management repositories.
Dependencies resolved.
==================================================================
 Package                            Architecture                Version                                Repository                               Size
==================================================================
Removing:
 ant                                noarch                       1.10.5-1.module+el8+2438+c99a8a1e      @rhel-8-for-x86_64-appstream-rpms       451 k
Removing unused dependencies:
 ant-lib                            noarch                       1.10.5-1.module+el8+2438+c99a8a1e      @rhel-8-for-x86_64-appstream-rpms       2.2 M
 java-1.8.0-openjdk                 x86_64                       1:1.8.0.322.b06-2.el8_5                @rhel-8-for-x86_64-appstream-rpms       841 k
 java-1.8.0-openjdk-devel           x86_64                       1:1.8.0.322.b06-2.el8_5                @rhel-8-for-x86_64-appstream-rpms       41 M
 ttmkfdir                           x86_64                       3.0.9-54.el8                           @rhel-8-for-x86_64-appstream-rpms       128 k
 xorg-x11-fonts-Type1               noarch                       7.5-19.el8                             @rhel-8-for-x86_64-appstream-rpms       863 k

Transaction Summary
==================================================================

Freed space: 45 M
Is this ok [y/N]: y
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                              1/1
  Erasing          : ant-1.10.5-1.module+el8+2438+c99a8a1e.noarch                                                 1/6
  Erasing          : java-1.8.0-openjdk-devel-1:1.8.0.322.b06-2.el8_5.x86_64                                      2/6
  Running scriptlet: java-1.8.0-openjdk-devel-1:1.8.0.322.b06-2.el8_5.x86_64                                      2/6
  Erasing          : ant-lib-1.10.5-1.module+el8+2438+c99a8a1e.noarch                                             3/6
  Erasing          : java-1.8.0-openjdk-1:1.8.0.322.b06-2.el8_5.x86_64                                            4/6
  Running scriptlet: java-1.8.0-openjdk-1:1.8.0.322.b06-2.el8_5.x86_64                                            4/6
  Erasing          : xorg-x11-fonts-Type1-7.5-19.el8.noarch                                                       5/6
  Running scriptlet: xorg-x11-fonts-Type1-7.5-19.el8.noarch                                                       5/6
  Erasing          : ttmkfdir-3.0.9-54.el8.x86_64                                                                 6/6
  Running scriptlet: ttmkfdir-3.0.9-54.el8.x86_64                                                                 6/6
  Verifying        : ant-1.10.5-1.module+el8+2438+c99a8a1e.noarch                                                 1/6
  Verifying        : ant-lib-1.10.5-1.module+el8+2438+c99a8a1e.noarch                                             2/6
  Verifying        : java-1.8.0-openjdk-1:1.8.0.322.b06-2.el8_5.x86_64                                            3/6
  Verifying        : java-1.8.0-openjdk-devel-1:1.8.0.322.b06-2.el8_5.x86_64                                      4/6
  Verifying        : ttmkfdir-3.0.9-54.el8.x86_64                                                                 5/6
  Verifying        : xorg-x11-fonts-Type1-7.5-19.el8.noarch                                                       6/6
Installed products updated.

Removed:
  ant-1.10.5-1.module+el8+2438+c99a8a1e.noarch     ant-lib-1.10.5-1.module+el8+2438+c99a8a1e.noarch     java-1.8.0-openjdk-1:1.8.0.322.b06-2.el8_5.x86_64
  java-1.8.0-openjdk-devel-1:1.8.0.322.b06-2.el8_5.x86_64     ttmkfdir-3.0.9-54.el8.x86_64   xorg-x11-fonts-Type1-7.5-19.el8.noarch

Complete!
----

=== dnf module disable

----
dnf module disable <module_name:stream>
----

Disables a particular stream of a module. Disabling a module removes the previously enabled access to the repository packages in that module stream.

*Example:*

The following command disables stream `2.10` of the `scala` module:

----
$ sudo dnf module disable  scala:2.10
Updating Subscription Management repositories.
Last metadata expiration check: 0:18:31 ago on Tue 01 Feb 2022 09:09:19 AM PST.
Only module name is required. Ignoring unneeded information in argument: 'scala:2.10'
Dependencies resolved.
=====================================================================================
 Package                      Architecture        Version    Repository   Size
=====================================================================================
Disabling module profiles:
 scala/common
Disabling modules:
 scala

Transaction Summary
======================================================================================
Is this ok [y/N]: y
Complete!
----

=== dnf module switch-to

----

sudo dnf module [options] switch-to <module>:<stream>
----

Switches the current installed module to the one defined by `<module>:<stream>`. If the version is newer than the one presently installed, the switch is deemed `Upgraded`. If the version is older than the one presently installed, the switch is deemed `Downgraded`.

*Example:*

The following command switches the installed version of Node.js to version 16. The command uses the `-y` option to allow installation to proceed without user confirmation. The result displays portions of the start of the switch-to process and the end of the process:

----
$ sudo dnf module switch-to nodejs:16 -y
Updating Subscription Management repositories.
Last metadata expiration check: 2:14:26 ago on Wed 09 Feb 2022 08:06:21 AM PST.
Dependencies resolved.
========================================================================================================================================================
 Package                     Architecture        Version                                                 Repository                           Size
========================================================================================================================================================
Upgrading:
 nodejs                      x86_64               1:16.13.1-3.module+el8.5.0+13548+45d748af              rhel-8-for-x86_64-appstream-rpms      12 M
 nodejs-docs                 noarch               1:16.13.1-3.module+el8.5.0+13548+45d748af              rhel-8-for-x86_64-appstream-rpms     8.7 M
 nodejs-full-i18n            x86_64               1:16.13.1-3.module+el8.5.0+13548+45d748af              rhel-8-for-x86_64-appstream-rpms     7.6 M
 npm                         x86_64               1:8.1.2-1.16.13.1.3.module+el8.5.0+13548+45d748af      rhel-8-for-x86_64-appstream-rpms     1.9 M
Switching module streams:
 nodejs     10 -> 16
.
.
.
Installed products updated.

Upgraded:
  nodejs-1:16.13.1-3.module+el8.5.0+13548+45d748af.x86_64  nodejs-docs-1:16.13.1-3.module+el8.5.0+13548+45d748af.noarch   nodejs-full-i18n-1:16.13.1-3.module+el8.5.0+13548+45d748af.x86_64
  npm-1:8.1.2-1.16.13.1.3.module+el8.5.0+13548+45d748af.x86_64

Complete!
----

=== dnf module reset

----
dnf module reset [options] <module_name>
----

Instead of using `dnf module switch-to`, you can use  `dnf module reset` along with `dnf module install` to install an alternative module version on the local computer.

*Example:*

The following uses `dnf module reset` along with `dnf module install` to install the module `nodjs:16` over an existing, older version of Node.js. The results show the before and after calls to `node --version`. Also, the result is shown in abbreviated portions in order to economize on displaying screen output:

----
$ node --version
v10.24.0

$ sudo dnf module reset nodejs -y
.
.
.
Disabling module profiles:
 nodejs/common
Resetting modules:
 nodejs

Transaction Summary
==================================

Complete!

$ sudo dnf module install nodejs:16 -y
Updating Subscription Management repositories.
Last metadata expiration check: 2:34:13 ago on Wed 09 Feb 2022 08:06:21 AM PST.
.
.
.
Installed products updated.

Upgraded:
  nodejs-1:16.13.1-3.module+el8.5.0+13548+45d748af.x86_64                   nodejs-docs-1:16.13.1-3.module+el8.5.0+13548+45d748af.noarch              nodejs-full-i18n-1:16.13.1-3.module+el8.5.0+13548+45d748af.x86_64
  npm-1:8.1.2-1.16.13.1.3.module+el8.5.0+13548+45d748af.x86_64

Complete!

$ node --version
v16.13.1
----

== Module installation commands

----
sudo dnf install [options] <package_name>
----

Installs an application or package on the local system. Must be entered as root.

The following command installs the Ant build tool. The `--nodocs` option installs the package without its documentation:

----
sudo dnf install --nodocs ant
----

The following command installs `buildah`, which is used to create container images for Red Hat Enterprise Linux. The command also installs the `podman` container manager. The `--best` option installs the best versions of the packages, not necessarily the most recent versions:

----
sudo dnf install --best buildah podman
----

The following command installs the `llvm-toolset` package, which includes the LLVM compiler infrastructure framework, the Clang compiler for the C and C++ languages, the LLDB debugger, and related tools for code analysis:

----
sudo dnf install llvm-toolset
----

The following command installs a group of packages associated with tools typically used by programmers and software developers. The packages include Python, Perl, `gcc`, and `make`, to name a few:

----
sudo dnf group install "Development Tools"
----

The following command installs the Go programming language along with associated tools and libraries:

----
sudo dnf install go-toolset
----

The following command installs the Apache HTTP web server:

----
sudo dnf install httpd
----

The following command installs the nginx web server:

----
sudo dnf install nginx
----

The following command installs the MariaDB database server:

----
sudo dnf install mariadb
----

The following command installs the MySQL database server:

----
sudo dnf install mysql
----

The following command installs the Postgres database server:

----
sudo dnf install postgresql
----

The following command installs the Postgres database server using the `<module>:<stream>` syntax:

----
sudo dnf module install postgresql:9.6
----

The following command installs the Apache Maven framework for programming and managing Java applications:

----
sudo dnf install maven
----

The following command installs the Node.js programming environment:

----
sudo dnf install nodejs
----

The following command installs version 11 of the Java Development Kit:

----
sudo dnf install java-11-openjdk-devel
----

The following command installs version 8 of the Java Development Kit:

----
sudo dnf install java-1.8.0-openjdk-devel
----

The following command installs the Perl programming language and associated tools and libraries:

----
sudo dnf install perl
----

The following command installs the PHP programming language and associated tools and libraries:

----
sudo dnf install php
----

The following command installs the Python 2 programming language and associated tools and libraries:

----
sudo dnf install python2
----

The following command installs the Python 3 programming language and associated tools and libraries:

----
sudo dnf install python3
----

The following command installs the Redis database and message broker:

----
sudo dnf install redis
----

The following command installs the Ruby programming language and associated tools and libraries:

----
sudo dnf install ruby
----

The following command installs the Rust programming language and associated tools and libraries:

----
sudo dnf install rust-toolset
----

The following command installs the Scala programming language and associated tools and libraries:

----
sudo dnf install scala
----

The following command installs the SWIG interface compiler, which connects programs written in C and C++ with scripting languages such as Perl, Python, Ruby, and Tcl:

----
sudo dnf install swig
----

The following command installs the SystemTap tool, which allows users to study and monitor the activities of the operating system (particularly, the kernel) in fine detail:

----
sudo dnf install systemtap
----

The following command installs the Valgrind tool for debugging and profiling Linux programs:

----
sudo dnf install valgrind
----

The following command installs the Varnish web application accelerator, which can also be used as a caching HTTP reverse proxy:

----
sudo dnf install varnish
----
